### ISSUE TITLE
runtime文件夹不存在时，不会自动创建，报错

### ISSUE THREAD

**Issue by Emiyaa** [phalapi/kernal#14]
Uncaught exception 'PhalApi\Exception\InternalServerErrorException' with message 'Interal Server Error: Failed to log into file, because permission denied:

**Comment by collinxz-coder** [comment]
这个问题是因为传递给 `is_writeable` 参数的目录是需要新建的目录，但是这个时候目录还不存在，所以 `is_writeable` 会返回 false，然后就跑出了异常。代码在 Logger/FileLogger.php 文件的 65 行。

**Comment by collinxz-coder** [comment]
> Uncaught exception 'PhalApi\Exception\InternalServerErrorException' with message 'Interal Server Error: Failed to log into file, because permission denied:

这个问题是因为传递给 `is_writeable` 参数的目录是需要新建的目录，但是这个时候目录还不存在，所以 `is_writeable` 会返回 false，然后就跑出了异常。代码在 Logger/FileLogger.php 文件的 65 行。

**Comment by collinxz-coder** [comment]
@Emiyaa 需要给 runtime 目录可写权限。
```shell
$ chmod o+w runtime/
```

**Comment by Emiyaa** [comment]
> @Emiyaa 需要给 runtime 目录可写权限。
> 
> ```shell
> $ chmod o+w runtime/
> ```

我现在是把文件夹删了，更新到正式站，然后他没有自动创建此目录，程序运行的时候又会使用到。
我寻思使用前肯定得判断这个文件夹存在不

**Comment by phalapi** [comment]
框架底层会先判断目录是否存在，不存在会自动创建。
但如果没有权限，则会创建失败。如果是调试模式就会显示异常提示，如果非调试模式，就会静默失败，不写日志。

**Comment by Emiyaa** [comment]
> 框架底层会先判断目录是否存在，不存在会自动创建。
> 但如果没有权限，则会创建失败。如果是调试模式就会显示异常提示，如果非调试模式，就会静默失败，不写日志。

但是我根目录给的是777，还是不能创建

**Comment by Emiyaa** [comment]
> 框架底层会先判断目录是否存在，不存在会自动创建。
> 但如果没有权限，则会创建失败。如果是调试模式就会显示异常提示，如果非调试模式，就会静默失败，不写日志。

有runtime目录是可以的，现在的情况是没有判断runtime目录是否存在

**Comment by collinxz-coder** [comment]
`kernal/src/Logger/FileLogger.php`这个文件里面抛出的异常，这里只判断了是否可写，如果目录不存，在这个时候 is_writeable() 就会返回 false，然后就抛出了 InternalServerErrorException
```php
if (!file_exists($folder)) {
    if ($this->debug) {
        // 调试时，显示创建，更友好的提示
        if (!is_writeable($this->logFolder)) {
            throw new InternalServerErrorException(\PhalAPi\T('Failed to log into file, because permission denied: {path}', array('path' => Tool::getAbsolutePath($folder))));
        }
        mkdir($folder . '/', 0777, TRUE);
    } else {
        // 静默创建
        @mkdir($folder . '/', 0777, TRUE);
    }
}
```

**Comment by Emiyaa** [comment]
> `kernal/src/Logger/FileLogger.php`这个文件里面抛出的异常，这里只判断了是否可写，如果目录不存，在这个时候 is_writeable() 就会返回 false，然后就抛出了 InternalServerErrorException
> 
> ```
> if (!file_exists($folder)) {
>     if ($this->debug) {
>         // 调试时，显示创建，更友好的提示
>         if (!is_writeable($this->logFolder)) {
>             throw new InternalServerErrorException(\PhalAPi\T('Failed to log into file, because permission denied: {path}', array('path' => Tool::getAbsolutePath($folder))));
>         }
>         mkdir($folder . '/', 0777, TRUE);
>     } else {
>         // 静默创建
>         @mkdir($folder . '/', 0777, TRUE);
>     }
> }
> ```

w

**Comment by Emiyaa** [comment]
> `kernal/src/Logger/FileLogger.php`这个文件里面抛出的异常，这里只判断了是否可写，如果目录不存，在这个时候 is_writeable() 就会返回 false，然后就抛出了 InternalServerErrorException
> 
> ```
> if (!file_exists($folder)) {
>     if ($this->debug) {
>         // 调试时，显示创建，更友好的提示
>         if (!is_writeable($this->logFolder)) {
>             throw new InternalServerErrorException(\PhalAPi\T('Failed to log into file, because permission denied: {path}', array('path' => Tool::getAbsolutePath($folder))));
>         }
>         mkdir($folder . '/', 0777, TRUE);
>     } else {
>         // 静默创建
>         @mkdir($folder . '/', 0777, TRUE);
>     }
> }
> ```

我的意思是能不能在这先判断下这个目录是否存在，不存在创建下

**Comment by Emiyaa** [comment]
> `kernal/src/Logger/FileLogger.php`这个文件里面抛出的异常，这里只判断了是否可写，如果目录不存，在这个时候 is_writeable() 就会返回 false，然后就抛出了 InternalServerErrorException
> 
> ```
> if (!file_exists($folder)) {
>     if ($this->debug) {
>         // 调试时，显示创建，更友好的提示
>         if (!is_writeable($this->logFolder)) {
>             throw new InternalServerErrorException(\PhalAPi\T('Failed to log into file, because permission denied: {path}', array('path' => Tool::getAbsolutePath($folder))));
>         }
>         mkdir($folder . '/', 0777, TRUE);
>     } else {
>         // 静默创建
>         @mkdir($folder . '/', 0777, TRUE);
>     }
> }
> ```

你说的这个我知道

**Comment by Emiyaa** [comment]
额  我搞错了，另一个同事更新的时候忘了关debug，没注意，抱歉了
